const admin = require('firebase-admin');
const { generatePaper } = require('../services/paperGeneratorService');
const supabase = require('../config/supabaseClient');
const fs = require('fs');
const path = require('path');

const generateDraft = async (req, res) => {
  try {
    const { courseTitle } = req.body;
    if (!courseTitle) {
      return res.status(400).json({ error: 'Course Title is required' });
    }

    const paper = await generatePaper(courseTitle);
    
    // Save draft to DB for HOD approval (Implementation omitted for brevity)
    
    res.json({
      message: 'Draft generated successfully!',
      paper: paper
    });

  } catch (error) {
    console.error("Draft Generation Error:", error.message);
    res.status(400).json({ error: error.message });
  }
};

const downloadPdf = async (req, res) => {
  // Keeping this for backward compatibility or future use, but the primary flow is generateDraft -> Frontend Print -> Save Final
  try {
    const courseTitle = req.body.courseTitle;
    if (!courseTitle) {
      return res.status(400).json({ error: 'courseTitle is required' });
    }
    const paper = await generatePaper(courseTitle);
    const { generatePDFBuffer } = require('../services/pdfService');
    const pdfBuffer = await generatePDFBuffer(paper);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${courseTitle.replace(/\s+/g, '_')}_Paper.pdf"`);
    res.send(pdfBuffer);
  } catch (error) {
    console.error("Error in downloadPdf:", error);
    res.status(500).json({ error: error.message || 'Failed to download PDF' });
  }
};

/**
 * Saves a finalized paper PDF (generated by the frontend) to Supabase and Firestore.
 */
const saveFinalPaper = async (req, res) => {
  try {
    const { paper } = req.body;
    if (!paper || !paper.courseTitle) {
      return res.status(400).json({ error: 'Paper JSON with courseTitle is required' });
    }

    const { generatePDFBuffer } = require('../services/pdfService');
    const pdfBuffer = await generatePDFBuffer(paper);
    
    // 1. Upload to Supabase 'final-papers' bucket
    const fileName = `${Date.now()}_Final_${paper.courseTitle.replace(/\s+/g, '_')}.pdf`;
    
    const { data: uploadData, error: uploadError } = await supabase
      .storage
      .from('final-papers')
      .upload(fileName, pdfBuffer, {
        contentType: 'application/pdf',
        upsert: false
      });

    if (uploadError) {
      throw new Error(`Supabase upload failed: ${uploadError.message}`);
    }

    const { data: { publicUrl } } = supabase
      .storage
      .from('final-papers')
      .getPublicUrl(fileName);

    console.log(`Uploaded Final Paper to Supabase: ${publicUrl}`);

    // 2. Save pointer to Firestore
    if (admin.apps.length > 0) {
      const db = admin.firestore();
      const bankRef = db.collection('question_banks').doc(paper.courseTitle.replace(/\s+/g, '_').toLowerCase());
      
      const finalPaperRef = bankRef.collection('final_papers').doc(fileName);
      await finalPaperRef.set({
        courseTitle: paper.courseTitle,
        finalPdfUrl: publicUrl,
        createdAt: admin.firestore.FieldValue.serverTimestamp()
      });
    }

    res.json({
      message: 'Final paper securely saved to Supabase',
      url: publicUrl
    });

  } catch (error) {
    console.error("Error in saveFinalPaper:", error);
    res.status(500).json({ error: 'Failed to save final paper' });
  }
};

const downloadDraft = async (req, res) => {
  try {
    const { paper } = req.body;
    if (!paper || !paper.courseTitle) {
      return res.status(400).json({ error: 'Paper JSON is required' });
    }
    
    const { generatePDFBuffer } = require('../services/pdfService');
    const pdfBuffer = await generatePDFBuffer(paper);
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${paper.courseTitle.replace(/\s+/g, '_')}_Draft.pdf"`);
    res.send(pdfBuffer);
  } catch (error) {
    console.error("Error in downloadDraft:", error);
    res.status(500).json({ error: 'Failed to download draft' });
  }
};

module.exports = {
  generateDraft,
  downloadPdf,
  saveFinalPaper,
  downloadDraft
};
